url: "https://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-KendraMaria" # the subpath of your site, e.g. /blog
title: "Top 5" # the name of your site, e.g. ACME Corp.

collections:
  chats:
    output: true
  animals:
    output: true
plugins:
  - jekyll-admin

nav-links:
  - name: "chats"
    link: "chats.html"
  - name: "animals"
    link: "animals.html"
  - name: "fascinant"
      link: "fascinant.html"
  - name: "home"
    link: "index.html"
