url: "https://eracom-id471.github.oi" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-kendraMaria" # the subpath of your site, e.g. /blog
title: "chats" # the name of your site, e.g. ACME Corp.

collections:
  chats:
    output: true

plugins:
  - jekyll-admin
